### PR TITLE
Send checksums with downloaded content

### PR DESCRIPTION
**Pull request by dbrower**
This allows end-to-end checksum verification of our content.

### CODE REVIEW

**Comment by msuhovec** [comment]
so of course, after no code changes for a year, Don changes the one file I
have out for change 🤔

**Comment by dbrower** [comment]
@msuhovec That is why I noticed this didn't get merged! The date on the commit is from over a year ago. I'm sorry for messing you up.

**Comment by msuhovec** [comment]
You talked about it yesterday- I thought it was a new change. Didn't
realize it was an old request.

**Comment by dbrower** [comment]
The commit was old, but I didn't make a PR until now. I wanted to get it in before you made changes!

**Pull request merged**
