### PR TITLE
Adding GoDeps for Disadis

### PR DESCRIPTION
**Pull request by msuhovec**
#1 Adding GoDeps dependencies for disadis.

### CODE REVIEW

**Comment by dbrower** [comment]
Does this work with the Go 1.5 vendor experiment? I thought that required everything to be in the `vendor` directory, not the `GoDeps` directory.

**Comment by msuhovec** [comment]
I'm vacillating  between the two. Having used  both now, I find GoDeps much
easier once it's all built and in the repo; however,  when one's trying to
get stuff to work locally in development, it's nice to have the 1.5 hook so
one can make a vendor dir and throw packages in there .

Mark Suhovecky
Sr. Systems Administrator
University of Notre Dame
208 Hesburgh Library
574-631-9269
msuhovec@nd.edu

**Comment by msuhovec** [comment]
Go 1.5 vendor/ experiment

Godep has preliminary support for the Go 1.5 vendor/ experiment
<https://github.com/golang/go/commit/183cc0cd41f06f83cb7a2490a499e3f9101befff>
utilizing
the same environment variable that the go tooling itself supports: export
GO15VENDOREXPERIMENT=1

When GO15VENDOREXPERIMENT=1 godep will write the vendored code into the
local package's vendor directory. AGodeps/Godeps.json file is created, just
like during normal operation. The vendor experiment is not compatible with
rewrites.

There is currently no automated migration between the old Godeps workspace
and the vendor directory, but the following steps should work:

$ unset GO15VENDOREXPERIMENT
$ godep restore
# The next line is only needed to automatically undo rewritten imports that were
# created with godep save -r.
$ godep save ./...
$ rm -rf Godeps
$ export GO15VENDOREXPERIMENT=1
$ godep save ./...
$ git add -A
# You should see your Godeps/_workspace/src files "moved" to vendor/.

**Comment by msuhovec** [comment]
OK - I used the Godep support for vendoring, and regenerated the godeps workspace, which is written to vendor when GO15VENDOREXPERIMENT=1

**Comment by msuhovec** [comment]
At some point I should redo Bendo , so they're consistent. Bendo adds the godep path to GOPATH at present.

**Comment by dbrower** [comment]
Lets do it! Need to change puppet class to set the right env vars, too. ( @msuhovec Didn't you already do this?)

**Comment by msuhovec** [comment]
The puppet class lib_go "might" work with the 1.5 var set, but it's doing
extra stuff to add Godeps to the path that it no longer needs.

**Pull request merged**
